/* Autogenerated by /usr/bin/halcompile on Sun Jan 14 14:58:13 2024 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:odometer:");
MODULE_INFO(linuxcnc, "pin:velocity:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:distance:float:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:active:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:cycles:u32:0:out::None:None");
MODULE_INFO(linuxcnc, "param:trigger_distance:float:0:rw::3000:None");
MODULE_INFO(linuxcnc, "param:active_duration:u32:0:rw::15000:None");
MODULE_INFO(linuxcnc, "param:activate_on_boot:bit:0:rw::true:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_float_t *velocity;
    hal_float_t *distance;
    hal_bit_t *active;
    hal_u32_t *cycles;
    hal_float_t trigger_distance;
    hal_u32_t active_duration;
    hal_bit_t activate_on_boot;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_float_newf(HAL_IN, &(inst->velocity), comp_id,
        "%s.velocity", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->distance), comp_id,
        "%s.distance", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->active), comp_id,
        "%s.active", prefix);
    if(r != 0) return r;
    r = hal_pin_u32_newf(HAL_OUT, &(inst->cycles), comp_id,
        "%s.cycles", prefix);
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RW, &(inst->trigger_distance), comp_id,
        "%s.trigger-distance", prefix);
    inst->trigger_distance = 3000;
    if(r != 0) return r;
    r = hal_param_u32_newf(HAL_RW, &(inst->active_duration), comp_id,
        "%s.active-duration", prefix);
    inst->active_duration = 15000;
    if(r != 0) return r;
    r = hal_param_bit_newf(HAL_RW, &(inst->activate_on_boot), comp_id,
        "%s.activate-on-boot", prefix);
    inst->activate_on_boot = true;
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
RTAPI_MP_INT(count, "number of odometer");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of odometer");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("odometer");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "odometer.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        size_t i, j;
        int idx;
        char buf[HAL_NAME_LEN+1];
        const size_t length = strlen(names);
        for (i = j = idx = 0; i <= length; i++) {
            const char c = buf[j] = names[i];
            if ((c == ',') || (c == '\0')) {
                buf[j] = '\0';
                r = export(buf, idx);
                if(r != 0) {break;}
                idx++;
                j = 0;
            } else {
                if (++j == (sizeof(buf) / sizeof(buf[0]))) {
                    buf[j - 1] = '\0';
                    rtapi_print_msg(RTAPI_MSG_ERR,"names: \"%s\" too long\n", buf);
                    r = -EINVAL;
                    break;
                }
            }
        }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef velocity
#define velocity (0+*__comp_inst->velocity)
#undef distance
#define distance (*__comp_inst->distance)
#undef active
#define active (*__comp_inst->active)
#undef cycles
#define cycles (*__comp_inst->cycles)
#undef trigger_distance
#define trigger_distance (__comp_inst->trigger_distance)
#undef active_duration
#define active_duration (__comp_inst->active_duration)
#undef activate_on_boot
#define activate_on_boot (__comp_inst->activate_on_boot)


#line 16 "odometer/odometer.comp"

static unsigned time_active_counter;
static double distance;
static double current_distance;
static double dx;

FUNCTION(_) {
    dx = velocity * (fperiod);
    distance += dx;

    if (active) {
        time_active_counter += (period / 1000000);
        active = time_active_counter > active_duration;
    } else {
        if (activate_on_boot) {
            activate_on_boot = false;
            active = true;
            cycles += 1;
            time_active_counter = 0;
            current_distance = 0;
        }
        current_distance += dx;
        if (current_distance > trigger_distance) {
            active = true;
            cycles += 1;
            time_active_counter = 0;
            current_distance = 0;
        }
    }
}

static int __comp_get_data_size(void) { return 0; }
